### ISSUE TITLE
Is the INSTALL.md correct?

### ISSUE THREAD

**Issue by mddrill** [dannye/pokeyellow-gen-II#1]
I think there may be mistakes in the readmes. The README.md has the same md5 hash as the regular pokeyellow and the INSTALL.md for Mac says to clone that one, not this one.

**Comment by dannye** [comment]
I have not bothered to "fix" the install instructions for any of my hacks.
If you can follow along with how to clone and build pokeyellow, then you can clone and build pokeyellow-gen-II

**Comment by mddrill** [comment]
I'm getting this error on make

> ERROR: wram.asm(536):
> 	Constant mustn't be negative: -528
> make: *** [wram.o] Error 5

The full output is

> rgbasm -h -o audio.o audio.asm
> rgbasm -h -o main.o main.asm
> warning: main.asm(15) -> home.asm(168) -> home/overworld.asm(1764):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(15) -> home.asm(4567):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(15) -> home.asm(4751):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(15) -> home.asm(4771) -> home/predef.asm(26):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(24) -> engine/titlescreen.asm(269):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(38) -> engine/cable_club.asm(312):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(62) -> engine/menu/text_ids2.asm(27):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(75) -> engine/overworld/check_player_state.asm(108):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(87) -> engine/items/items.asm(16):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(144) -> engine/menu/start_sub_menus.asm(121):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(759) -> engine/slot_machine.asm(455):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(768) -> engine/battle/trainer_ai.asm(54):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(768) -> engine/battle/trainer_ai.asm(375):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(785) -> engine/battle/core.asm(3318):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(785) -> engine/battle/core.asm(5867):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(785) -> engine/battle/core.asm(7034):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(221):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(263):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(284):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(291):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(305):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(326):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(340):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(382):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(438):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(452):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(515):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(543):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(613):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(760):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(823):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(956):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(1019):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(1117):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(1124):
> 	Empty entry in list of 8-bit elements (treated as 0).
> warning: main.asm(792) -> engine/trade.asm(50):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1774) -> engine/battle/battle_transitions.asm(65):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1778) -> engine/palettes.asm(20):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1910) -> engine/battle/animations.asm(243):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1910) -> engine/battle/animations.asm(484):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1910) -> engine/battle/animations.asm(693):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1910) -> engine/battle/animations.asm(1132):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(1914) -> engine/overworld/ssanne.asm(20):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2059) -> engine/printer.asm(12) -> engine/printer/serial.asm(32):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2059) -> engine/printer.asm(12) -> engine/printer/serial.asm(452):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2065) -> engine/unknown_ea3ea.asm(247):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2065) -> engine/unknown_ea3ea.asm(712):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2065) -> engine/unknown_ea3ea.asm(830):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2065) -> engine/unknown_ea3ea.asm(872):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2081) -> engine/bank3e.asm(1) -> engine/surfing_minigame.asm(387):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2081) -> engine/bank3e.asm(1) -> engine/surfing_minigame.asm(675):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2081) -> engine/bank3e.asm(1) -> engine/surfing_minigame.asm(1979):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2081) -> engine/bank3e.asm(2) -> engine/yellow_intro.asm(101):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2081) -> engine/bank3e.asm(2) -> engine/yellow_intro.asm(988):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2081) -> engine/bank3e.asm(5) -> engine/animated_objects_3e.asm(394):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2086) -> engine/bank3f.asm(7) -> engine/pikachu_movement.asm(124):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> warning: main.asm(2086) -> engine/bank3f.asm(7) -> engine/pikachu_movement.asm(490):
> 	'JP [HL]' is obsolete, use 'JP HL' instead.
> rgbasm -h -o text.o text.asm
> rgbasm -h -o wram.o wram.asm
> ERROR: wram.asm(536):
> 	Constant mustn't be negative: -528
> make: *** [wram.o] Error 5

**Comment by dannye** [comment]
Ah, you have to use rgbds v0.2.5 (before negative space declarations were removed, and before unions were added)

I will try to update it soon, so you can continue using the most recent version of rgbds v0.3.6

**Comment by dannye** [comment]
Unrelated to the build error from the wrong rgbds version, I just noticed the warnings that look like:
```
warning: main.asm(790) -> engine/menu/pokedex.asm(707) -> data/pokedex_entries.asm(221):
Empty entry in list of 8-bit elements (treated as 0).
```

That's a problem in the base pokeyellow repo, introduced in this commit:
https://github.com/pret/pokeyellow/commit/8b82d13dd520d387f926db819fda949ad0021b53#diff-f88b857f57faa15da30ce6f00a038bbcR221

I'll take care of that too real quick.
